<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <title>Polar Bear Footprints</title>
        <meta property="og:description" content="Polar bears can communicate via footprints" />
    </head>
    <body>
        <a href="http://gizmodo.com/polar-bears-can-communicate-via-footprints-1680986062">
            <img src="https://i.kinja-img.com/gawker-media/image/upload/s--P-Oz7-so--/c_scale,fl_progressive,q_80,w_800/pceadxep1gfkntmxd39x.jpg">
        </a>
        Image via Flickr

        <img src="/pbfp.png">

        <script async src="/assets/js/all.js?<?php echo time(); ?>"></script>
        <script>
            var pbfp = pbfp || {};
            if (typeof(pbfp) === 'object') {
                pbfp.sn = "facebook";  //social network
                pbfp.sid = "123456789"; //social id
            }
        </script>
    </body>
</html>
    
